from __future__ import annotations

from datetime import UTC, datetime
from typing import Annotated, Any, ClassVar, Literal, Self, TypeVar

from pydantic import BaseModel, ConfigDict, Field, ValidationInfo, field_validator
from typing_extensions import TypeAliasType

from feishu_task_cli.artifacts.canonical import artifact_hash
from feishu_task_cli.errors import ArtifactIntegrityError

NonEmptyString = Annotated[str, Field(min_length=1)]
UtcDateTime = Annotated[
    datetime,
    Field(json_schema_extra={"pattern": r"^(?:.*Z|.*[+]00:00)$"}),
]
JsonValueNoFloat = TypeAliasType(
    "JsonValueNoFloat",
    "str | int | bool | None | list[JsonValueNoFloat] | dict[str, JsonValueNoFloat]",
)


class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, str_strip_whitespace=True)


class ArtifactV1(StrictModel):
    hash_field: ClassVar[str]
    schema_version: Literal["1"] = "1"
    artifact_type: str
    created_at: UtcDateTime
    tool_version: NonEmptyString

    @field_validator("created_at")
    @classmethod
    def require_utc(cls, value: datetime) -> datetime:
        if value.tzinfo is None or value.utcoffset() != UTC.utcoffset(value):
            raise ValueError("timestamp must use UTC")
        return value

    @classmethod
    def build(cls, **data: Any) -> Self:
        """Create and hash a new artifact; ordinary validation never re-signs input."""
        if cls.hash_field in data:
            raise ArtifactIntegrityError(f"{cls.hash_field} is generated by build()")
        return cls.model_validate(
            {**data, cls.hash_field: "0" * 64},
            context={"artifact_build_token": _ARTIFACT_BUILD_TOKEN},
        )


ArtifactT = TypeVar("ArtifactT", bound=ArtifactV1)


_ARTIFACT_BUILD_TOKEN = object()


def bind_hash(artifact: ArtifactT, hash_field: str, info: ValidationInfo) -> ArtifactT:
    expected = artifact_hash(artifact, hash_field=hash_field)
    supplied = getattr(artifact, hash_field)
    is_builder = bool(
        info.context and info.context.get("artifact_build_token") is _ARTIFACT_BUILD_TOKEN
    )
    if not is_builder and supplied != expected:
        raise ArtifactIntegrityError(f"{hash_field} does not match canonical artifact content")
    if is_builder:
        object.__setattr__(artifact, hash_field, expected)
    return artifact
